module.exports = {
  FB_PAGE_TOKEN:
    "EAAXxCGnD43cBO51pYA2R6XhqqR1HZALtEHzfZCnapmFyLwEjBL948VtD9T4eYNZBnXLenG736g9f8n7WGYxGEskFIYnwfO1TZARW4DBUUdZCsIqxFsJ5P9HvD1eO1735oQWVVB53wDma1BQQIghPLXPVYioda9q4nzMC5ClZCOuqLDTf0ClQpdzzaqGVcM7ZCIKIjCb4yPWT0mDxV5DfAZDZD",
  FB_VERIFY_TOKEN: "",
  FB_APP_SECRET: "",
  SERVER_URL: "",
  GOOGLE_PROJECT_ID: "",
  DF_LANGUAGE_CODE: "",
  GOOGLE_CLIENT_EMAIL: "",
  GOOGLE_PRIVATE_KEY: "",
};
